import { writeFileSync } from "fs";
import { dirname, resolve } from "path";
import recursiveReaddir from "recursive-readdir";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const BASE_DIR = resolve(__dirname, "..\\static\\asset");
const assetList = await recursiveReaddir(BASE_DIR);
const assetJSON = {
  ["_".repeat(2 << 3) + "ATTENTION" + "_".repeat(2 << 3)]:
    "This file is automatically generated, do not edit manually!",
};
for (const path of assetList) {
  const relativePathList = path.replace(`${BASE_DIR}\\`, "").split("\\");
  assetJSON[relativePathList.join("_").replace(/\.(png|jpg)/, "")] = relativePathList.join("/");
}
writeFileSync(resolve(__dirname, "../src/client/asset.json"), JSON.stringify(assetJSON, null, 2));
